---
- name: setup mongodb
  hosts: mongodb
  become: yes

  roles:
   - mongodb

- name: setup mysql
  hosts: mysql
  become: yes

  roles:
   - mysql

- name: setup redis
  hosts: redis
  become: yes

  roles:
   - redis

- name: setup rabbitmq
  hosts: rabbitmq
  become: yes

  roles:
   - rabbitmq